name: Reducer
version: 1.0
main: pies.Reducer.Main
author: hi12167pies
depend: [Citizens]
commands:
  reducer:
    usage: /reducer [gui]
    description: Open the reducer settings GUI
    aliases:
      - reduce
  reducermap:
    usage: /reducer create/add [map]
    description: Create a map at your current location
    permission: reducer.setmap
    permission-message: You cannot run this